### ISSUE TITLE
NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by ST9527** [protream/iquery#17]
I use pyenv to switch to python 3.5.
After I install it.It didn't work!
Keep throw this error: 

> Traceback (most recent call last):
  File "/Users/long/.pyenv/versions/myenv3/bin/iquery", line 7, in <module>
    from run import cli
  File "/Users/long/.pyenv/versions/myenv3/lib/python3.5/site-packages/run.py", line 3, in <module>
    from iquery.core import cli
  File "/Users/long/.pyenv/versions/myenv3/lib/python3.5/site-packages/iquery/core.py", line 21, in <module>
    requests.packages.urllib3.disable_warnings(SNIMissingWarning)
NameError: name 'requests' is not defined

 I have installed the `requests` by the way.

**Comment by pezy** [comment]
I met the error too. And I added `import requests` to `iquery/core.py`, then fixed.

check: https://github.com/pezy/iquery/commit/a696b9e99585e6107820c59d6971802c1237e7dc

**Comment by protream** [comment]
This is my mistake. Now it is fixed.
